### ISSUE TITLE
Issues with installing the gpsearch package

### ISSUE THREAD

**Issue by SannevE** [ablancha/gpsearch#1]
Dear ablancha,

Based on a paper by Guth & Sapsis (2022), who used your toolbox for adaptive sampling in a problem predicting extreme values of maritime responses, I would like to use the toolbox. However, I'm running into problems when I try to install it from Github. See below the error messages I get. Searching for these errors suggests that there is something wrong with the 'requirements' file (?) Could you help out? Thanks!

Kind regards,
Sanne 

USED COMMAND:
pip install git+https://github.com/ablancha/gpsearch.git

ERROR MESSAGE:
Collecting git+https://github.com/ablancha/gpsearch.git
  Cloning https://github.com/ablancha/gpsearch.git to <my temporary directory>
  Running command git clone --filter=blob:none --quiet https://github.com/ablancha/gpsearch.git '<my temporary directory>'
  Resolved https://github.com/ablancha/gpsearch.git to commit 8c5d77b3f0df803029d26828966274d6185c12e4
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gpsearch setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'=1.9.9'": Expected string_end
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ablancha** [comment]
Hi Sanne, I updated the req file; please let me know if that solved the problem.  If not, try to update setuptools and/or pip.  Thanks!

**Comment by SannevE** [comment]
Hi, thanks! It works now. I guess it was the single = instead of the double == in the requirements file?

**Comment by ablancha** [comment]
Yes!  Good catch
